<?php /** @var \Dfe\Markdown\Block\Init $this */ ?>
<?php
/**
 * 2015-10-25
 * Наш скрипт надо загружать именно через «text/x-magento-init».
 * Сначала я ошибочно загружал его через
 * df_page()->addPageAsset('Dfe_Markdown::main.js');
 * однако это приводило к тому, что содержимое редактора не показывалось
 * до клика по нему:
 * http://stackoverflow.com/questions/8349571
 * http://stackoverflow.com/questions/17086538
 */
?>
<script type='text/x-magento-init'>{"*": {"Dfe_Markdown/main": {}}}</script>
